apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          resources:
            requests:
              storage: 25Gi
    prometheusK8s:
      retention: 14d
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Filesystem
          resources:
            requests:
              storage: 300Gi
    prometheusOperator: {}
    k8sPrometheusAdapter: {}
    kubeStateMetrics: {}
    telemeterClient: {}
    openshiftStateMetrics: {}
    thanosQuerier: {}
    grafana: {}
